databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        fromDatabase:
          name: postgres
          property: connectionString
    - type: redis
      name: redis
      ipAllowList: []
      plan: free
      maxmemoryPolicy: noeviction