databases:
  - name: budget_app_database
    databaseName: budget_app_database_7wkx
    user: budget_app_database_7wkx_user

services: 
  - type: web
    name: budget_application
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false